version: "3.8"
services:
  blog-server: #docker run -it -v ${PWD}:/work -w /work -p 5003:5000 aimvector/python:1.0.0 /bin/sh
    container_name: python
    image: aimvector/python:1.0.0
    build:
      context: ./blog-server
      target: debug
    #working_dir: /work # uncomment for production
    #entrypoint: bin/sh # uncomment for production
    #stdin_open: true   # uncomment for production
    #tty: true          # uncomment for production
    volumes:
      - ./blog-server/src/:/work
    ports:
      - 5003:5000
      - 5678:5678
